# Generated by Django 6.1.1 on 2026-09-04 16:48

import django.db.models.expressions
from decimal import Decimal

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=32, unique=True)),
                (
                    "discount_type",
                    models.CharField(
                        choices=[
                            ("fixed", "Fixed amount"),
                            ("percentage", "Percentage"),
                        ],
                        max_length=12,
                    ),
                ),
                ("value", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "minimum_order",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                    ),
                ),
                ("valid_from", models.DateTimeField(blank=True, null=True)),
                ("valid_until", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ["code"]},
        ),
        migrations.AddField(
            model_name="order",
            name="coupon_code",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.CheckConstraint(
                condition=models.Q(("discount__lte", models.F("subtotal"))),
                name="orders_discount_not_above_subtotal",
            ),
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "total",
                        django.db.models.expressions.CombinedExpression(
                            django.db.models.expressions.CombinedExpression(
                                models.F("subtotal"),
                                "-",
                                models.F("discount"),
                            ),
                            "+",
                            models.F("shipping_cost"),
                        ),
                    )
                ),
                name="orders_total_matches_components",
            ),
        ),
        migrations.AddConstraint(
            model_name="coupon",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("discount_type", "fixed"),
                        ("value__gt", Decimal("0.00")),
                    ),
                    models.Q(
                        ("discount_type", "percentage"),
                        ("value__gt", Decimal("0.00")),
                        ("value__lte", Decimal("100.00")),
                    ),
                    _connector="OR",
                ),
                name="orders_coupon_value_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="coupon",
            constraint=models.CheckConstraint(
                condition=models.Q(("minimum_order__gte", Decimal("0.00"))),
                name="orders_coupon_minimum_order_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="coupon",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("valid_from__isnull", True),
                    ("valid_until__isnull", True),
                    ("valid_until__gt", models.F("valid_from")),
                    _connector="OR",
                ),
                name="orders_coupon_validity_window_valid",
            ),
        ),
    ]
