# Generated by Django 6.1.1 on 2026-09-04 14:42

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField(blank=True)),
                ("logo", models.ImageField(blank=True, upload_to="brands/")),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name_plural": "categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Collection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Watch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=180)),
                ("slug", models.SlugField(unique=True)),
                ("sku", models.CharField(max_length=64, unique=True)),
                ("description", models.TextField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "discount_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("stock", models.PositiveIntegerField(default=0)),
                (
                    "movement",
                    models.CharField(
                        choices=[
                            ("automatic", "Automatic"),
                            ("mechanical", "Mechanical"),
                            ("quartz", "Quartz"),
                        ],
                        max_length=16,
                    ),
                ),
                ("case_material", models.CharField(max_length=80)),
                (
                    "case_diameter_mm",
                    models.DecimalField(decimal_places=1, max_digits=4),
                ),
                ("strap_material", models.CharField(max_length=80)),
                ("dial_color", models.CharField(max_length=80)),
                ("water_resistance_m", models.PositiveSmallIntegerField()),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("women", "Women"),
                            ("men", "Men"),
                            ("unisex", "Unisex"),
                        ],
                        default="unisex",
                        max_length=10,
                    ),
                ),
                ("is_featured", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="watches",
                        to="catalog.brand",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="watches",
                        to="catalog.category",
                    ),
                ),
                (
                    "collections",
                    models.ManyToManyField(
                        blank=True, related_name="watches", to="catalog.collection"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WatchImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="watches/%Y/%m/")),
                ("alt_text", models.CharField(blank=True, max_length=180)),
                ("position", models.PositiveSmallIntegerField(default=0)),
                ("is_primary", models.BooleanField(default=False)),
                (
                    "watch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="catalog.watch",
                    ),
                ),
            ],
            options={
                "ordering": ["position", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="watch",
            index=models.Index(
                fields=["is_active", "-created_at"],
                name="catalog_wat_is_acti_8df7aa_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="watch",
            constraint=models.CheckConstraint(
                condition=models.Q(("price__gt", Decimal("0"))),
                name="catalog_watch_price_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="watch",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("discount_price__isnull", True),
                    models.Q(
                        ("discount_price__gt", Decimal("0")),
                        ("discount_price__lt", models.F("price")),
                    ),
                    _connector="OR",
                ),
                name="catalog_watch_discount_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="watchimage",
            constraint=models.UniqueConstraint(
                fields=("watch", "position"), name="catalog_watch_image_position_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="watchimage",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_primary", True)),
                fields=("watch",),
                name="catalog_one_primary_image_per_watch",
            ),
        ),
    ]
